import type { Metadata } from 'next';
import './globals.css';
// Panda CSS output (generated by `panda codegen && panda cssgen` before build).
import '../../styled-system/styles.css';
import { Providers } from '@/store/providers';

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || process.env.NEXT_PUBLIC_API_URL?.replace(/\/api\/v1\/?$/, '') || 'http://localhost:3000'),
  title: {
    default: 'طيبت — منصة التوافق الذكي والزواج الإسلامي',
    template: '%s | طيبت',
  },
  description:
    'طيبت منصة ذكية للتعارف والزواج للمسلمين حول العالم، تعتمد على الذكاء الاصطناعي لإيجاد التوافق الديني والحياتي بطريقة حلال وآمنة. Tayyibt is an AI-powered Muslim matchmaking platform.',
  keywords: ['زواج', 'تعارف', 'مسلمين', 'توافق', 'Muslim matchmaking', 'marriage', 'Tayyibt', 'طيبت'],
  openGraph: {
    title: 'طيبت — منصة التوافق الذكي والزواج الإسلامي',
    description: 'منصة ذكية للتعارف والزواج للمسلمين تعتمد على الذكاء الاصطناعي.',
    type: 'website',
    locale: 'ar_SA',
    siteName: 'طيبت',
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body className="min-h-screen font-sans antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
