#!/usr/bin/env python3
"""
Tayyibt VPS Deployment Script
Connects to the VPS, installs Docker, uploads the project, and starts all services.
"""

import os
import sys
import time
import stat
import tarfile
import secrets
import string
import io
import paramiko

# ── Config ────────────────────────────────────────────────────────────────────
VPS_HOST     = "145.14.158.100"
VPS_PORT     = 22
VPS_USER     = "root"
VPS_PASSWORD = os.environ.get('VPS_PASSWORD','')
APP_DIR      = "/opt/tayyibt"
COMPOSE_FILE = "docker-compose.vps.yml"
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directories/patterns to exclude from upload
EXCLUDE = {
    "node_modules", ".next", "dist", "build", ".git", "mobile",
    "__pycache__", ".venv", "venv", "env", "coverage", ".nyc_output",
    "logs", "tmp", "temp", ".cache",
    ".idea", ".vscode",
}
EXCLUDE_EXT = {".log", ".pid", ".h5", ".pkl", ".joblib", ".pyc", ".pyo",
               ".tsbuildinfo", ".sqlite", ".sqlite3", ".db"}

# ── Colours ───────────────────────────────────────────────────────────────────
G = "\033[92m"; Y = "\033[93m"; R = "\033[91m"; B = "\033[94m"; NC = "\033[0m"

def log(msg):   print(f"{G}[deploy]{NC} {msg}", flush=True)
def info(msg):  print(f"{B}[info  ]{NC} {msg}", flush=True)
def warn(msg):  print(f"{Y}[warn  ]{NC} {msg}", flush=True)
def err(msg):   print(f"{R}[error ]{NC} {msg}", flush=True); sys.exit(1)

# ── Secret generator ──────────────────────────────────────────────────────────
def gen_secret(n=40):
    alpha = string.ascii_letters + string.digits
    return "".join(secrets.choice(alpha) for _ in range(n))

# ── SSH helpers ───────────────────────────────────────────────────────────────
def ssh_connect():
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    log(f"Connecting to {VPS_USER}@{VPS_HOST}:{VPS_PORT} ...")
    client.connect(VPS_HOST, port=VPS_PORT, username=VPS_USER,
                   password=VPS_PASSWORD, timeout=60, banner_timeout=60, auth_timeout=60)
    log("Connected.")
    return client

def run(client, cmd, show=True, timeout=600):
    """Run a command, stream stdout/stderr, return exit code."""
    if show:
        info(f"$ {cmd[:120]}")
    _, stdout, stderr = client.exec_command(cmd, timeout=timeout, get_pty=True)
    output = []
    for line in stdout:
        line = line.rstrip()
        if line:
            print(f"   {line}", flush=True)
            output.append(line)
    exit_code = stdout.channel.recv_exit_status()
    return exit_code, "\n".join(output)

def run_ok(client, cmd, show=True):
    code, out = run(client, cmd, show)
    if code != 0:
        err(f"Command failed (exit {code}): {cmd}")
    return out

# ── Archive builder ───────────────────────────────────────────────────────────
def should_exclude(path):
    parts = set(path.replace("\\", "/").split("/"))
    if parts & EXCLUDE:
        return True
    _, ext = os.path.splitext(path)
    return ext in EXCLUDE_EXT

def build_archive():
    log("Building project archive (excluding node_modules, .next, etc.) ...")
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for root, dirs, files in os.walk(PROJECT_ROOT):
            # prune excluded dirs in-place
            dirs[:] = [d for d in dirs if d not in EXCLUDE and not d.startswith(".")]
            for fname in files:
                if fname.startswith(".env") and "example" not in fname and fname != ".env.production":
                    continue  # skip local env files
                full = os.path.join(root, fname)
                rel  = os.path.relpath(full, PROJECT_ROOT).replace("\\", "/")
                if should_exclude(rel):
                    continue
                _, ext = os.path.splitext(fname)
                if ext in EXCLUDE_EXT:
                    continue
                tar.add(full, arcname=rel)
    size_mb = buf.tell() / 1_048_576
    log(f"Archive size: {size_mb:.1f} MB")
    buf.seek(0)
    return buf

# ── Production env ────────────────────────────────────────────────────────────
def build_env_production():
    db_pass    = gen_secret(32)
    redis_pass = gen_secret(32)
    jwt_secret = gen_secret(64)

    env = f"""# Tayyibt production env — auto-generated by vps-deploy.py
# VPS: {VPS_HOST}

# Database
DATABASE_URL=postgresql://tayyibt_user:{db_pass}@postgres:5432/tayyibt_prod
DB_HOST=postgres
DB_PORT=5432
DB_USER=tayyibt_user
DB_PASSWORD={db_pass}
DB_NAME=tayyibt_prod

# Redis
REDIS_URL=redis://:{redis_pass}@redis:6379
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD={redis_pass}

# JWT
JWT_SECRET={jwt_secret}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# API
API_PORT=3000
API_HOST=0.0.0.0
NODE_ENV=production

# CORS
CORS_ORIGIN=http://{VPS_HOST}

# Public URLs (baked into Next.js builds)
NEXT_PUBLIC_API_URL=http://{VPS_HOST}/api/v1
NEXT_PUBLIC_WS_URL=http://{VPS_HOST}

# AI Service
AI_SERVICE_URL=http://ai-service:5000

# Email (configure later)
EMAIL_SERVICE=console
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=

# Scoring weights
WEIGHT_RELIGIOUS=0.30
WEIGHT_LIFESTYLE=0.25
WEIGHT_INTERESTS=0.20
WEIGHT_LOCATION=0.15
WEIGHT_OTHER=0.10

# Logging
LOG_LEVEL=info
"""
    # Write locally too so user has a record
    env_path = os.path.join(PROJECT_ROOT, ".env.production")
    with open(env_path, "w") as f:
        f.write(env)
    log(f"Generated .env.production with fresh secrets (saved locally too)")
    return env

# ── VPS setup ─────────────────────────────────────────────────────────────────
SETUP_SCRIPT = r"""
set -e
export DEBIAN_FRONTEND=noninteractive

echo "--- Updating packages ---"
apt-get update -qq
apt-get upgrade -y -qq

echo "--- Installing prerequisites ---"
apt-get install -y -qq curl git ca-certificates gnupg lsb-release ufw htop

echo "--- Installing Docker ---"
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    echo "Docker already installed: $(docker --version)"
fi

echo "--- Installing Docker Compose plugin ---"
if ! docker compose version &>/dev/null 2>&1; then
    apt-get install -y -qq docker-compose-plugin
fi
echo "Docker Compose: $(docker compose version)"

echo "--- Configuring firewall ---"
ufw default deny incoming  2>/dev/null || true
ufw default allow outgoing 2>/dev/null || true
ufw allow ssh              2>/dev/null || true
ufw allow 80/tcp           2>/dev/null || true
ufw allow 443/tcp          2>/dev/null || true
ufw --force enable         2>/dev/null || true

echo "--- Creating app directory ---"
mkdir -p /opt/tayyibt

echo "=== VPS setup complete ==="
"""

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print(f"\n{G}{'='*60}{NC}")
    print(f"{G}  Tayyibt -> VPS Deployment  {VPS_HOST}{NC}")
    print(f"{G}{'='*60}{NC}\n")

    # 1. Generate production env
    env_content = build_env_production()

    # 2. Connect to VPS
    client = ssh_connect()

    try:
        sftp = client.open_sftp()

        # 3. Run one-time VPS setup
        log("Running VPS setup (Docker, UFW, etc.) ...")
        run_ok(client, f"bash -c '{SETUP_SCRIPT.strip()}'", show=False)
        log("VPS setup done.")

        # 4. Upload project archive
        archive = build_archive()
        remote_archive = "/tmp/tayyibt_deploy.tar.gz"
        log(f"Uploading archive to {remote_archive} ...")

        archive_bytes = archive.read()
        with sftp.open(remote_archive, "wb") as f:
            f.write(archive_bytes)
        log(f"Upload complete ({len(archive_bytes)/1_048_576:.1f} MB)")

        # 5. Extract on VPS
        log("Extracting archive on VPS ...")
        run_ok(client, f"mkdir -p {APP_DIR} && tar -xzf {remote_archive} -C {APP_DIR} && rm {remote_archive}")

        # 6. Upload .env.production
        log("Uploading .env.production ...")
        env_remote = f"{APP_DIR}/.env.production"
        with sftp.open(env_remote, "w") as f:
            f.write(env_content)
        run_ok(client, f"chmod 600 {env_remote}", show=False)

        # 7. Set executable bits on scripts
        run_ok(client, f"chmod +x {APP_DIR}/scripts/*.sh 2>/dev/null || true", show=False)

        # 8. Build and launch containers
        log("Building Docker images (this takes 5-15 minutes) ...")
        compose_cmd = f"docker compose -f {APP_DIR}/{COMPOSE_FILE} --env-file {env_remote}"

        run_ok(client,
               f"cd {APP_DIR} && {compose_cmd} build --no-cache 2>&1",
               show=True)

        log("Starting all services ...")
        run_ok(client, f"cd {APP_DIR} && {compose_cmd} up -d --remove-orphans 2>&1")

        log("Waiting 40 s for services to stabilize ...")
        time.sleep(40)

        # 9. Status
        log("Container status:")
        run(client, f"docker compose -f {APP_DIR}/{COMPOSE_FILE} ps")

        log("Health checks:")
        run(client, f"curl -sf http://localhost/api/v1/health && echo '  Backend: OK' || echo '  Backend: FAILED'", show=False)
        run(client, f"curl -sf http://localhost/ -o /dev/null -w '%{{http_code}}' | grep -q 200 && echo '  Web: OK' || echo '  Web: FAILED'", show=False)

        sftp.close()

    finally:
        client.close()

    print(f"\n{G}{'='*60}{NC}")
    print(f"{G}  Deployment complete!{NC}")
    print(f"{G}{'='*60}{NC}")
    print(f"  Web:    http://{VPS_HOST}")
    print(f"  API:    http://{VPS_HOST}/api/v1")
    print(f"  Admin:  http://{VPS_HOST}/admin/")
    print(f"\n  Logs:  ssh root@{VPS_HOST} docker compose -f {APP_DIR}/{COMPOSE_FILE} logs -f")
    print(f"{G}{'='*60}{NC}\n")


if __name__ == "__main__":
    main()
